/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedMenusetIndexRouteImport } from './routes/_authenticated/menuset/index'
import { Route as AuthenticatedMenuIndexRouteImport } from './routes/_authenticated/menu/index'
import { Route as AuthenticatedMenusetIdRouteImport } from './routes/_authenticated/menuset/$id'
import { Route as AuthenticatedMenuIdRouteImport } from './routes/_authenticated/menu/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenusetIndexRoute =
  AuthenticatedMenusetIndexRouteImport.update({
    id: '/menuset/',
    path: '/menuset/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuIndexRoute = AuthenticatedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenusetIdRoute = AuthenticatedMenusetIdRouteImport.update({
  id: '/menuset/$id',
  path: '/menuset/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuIdRoute = AuthenticatedMenuIdRouteImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/menu/$id': typeof AuthenticatedMenuIdRoute
  '/menuset/$id': typeof AuthenticatedMenusetIdRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/menuset': typeof AuthenticatedMenusetIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/menu/$id': typeof AuthenticatedMenuIdRoute
  '/menuset/$id': typeof AuthenticatedMenusetIdRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/menuset': typeof AuthenticatedMenusetIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/_authenticated/menu/$id': typeof AuthenticatedMenuIdRoute
  '/_authenticated/menuset/$id': typeof AuthenticatedMenusetIdRoute
  '/_authenticated/menu/': typeof AuthenticatedMenuIndexRoute
  '/_authenticated/menuset/': typeof AuthenticatedMenusetIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/playground'
    | '/menu/$id'
    | '/menuset/$id'
    | '/menu'
    | '/menuset'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/playground'
    | '/menu/$id'
    | '/menuset/$id'
    | '/menu'
    | '/menuset'
    | '/user'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/playground/'
    | '/_authenticated/menu/$id'
    | '/_authenticated/menuset/$id'
    | '/_authenticated/menu/'
    | '/_authenticated/menuset/'
    | '/_authenticated/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menuset/': {
      id: '/_authenticated/menuset/'
      path: '/menuset'
      fullPath: '/menuset'
      preLoaderRoute: typeof AuthenticatedMenusetIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu/': {
      id: '/_authenticated/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menuset/$id': {
      id: '/_authenticated/menuset/$id'
      path: '/menuset/$id'
      fullPath: '/menuset/$id'
      preLoaderRoute: typeof AuthenticatedMenusetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu/$id': {
      id: '/_authenticated/menu/$id'
      path: '/menu/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof AuthenticatedMenuIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMenuIdRoute: typeof AuthenticatedMenuIdRoute
  AuthenticatedMenusetIdRoute: typeof AuthenticatedMenusetIdRoute
  AuthenticatedMenuIndexRoute: typeof AuthenticatedMenuIndexRoute
  AuthenticatedMenusetIndexRoute: typeof AuthenticatedMenusetIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMenuIdRoute: AuthenticatedMenuIdRoute,
  AuthenticatedMenusetIdRoute: AuthenticatedMenusetIdRoute,
  AuthenticatedMenuIndexRoute: AuthenticatedMenuIndexRoute,
  AuthenticatedMenusetIndexRoute: AuthenticatedMenusetIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
