/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as MenusetIndexRouteImport } from './routes/menuset/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as MenusetIdRouteImport } from './routes/menuset/$id'
import { Route as MenuIdRouteImport } from './routes/menu/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusetIndexRoute = MenusetIndexRouteImport.update({
  id: '/menuset/',
  path: '/menuset/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusetIdRoute = MenusetIdRouteImport.update({
  id: '/menuset/$id',
  path: '/menuset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIdRoute = MenuIdRouteImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu/$id': typeof MenuIdRoute
  '/menuset/$id': typeof MenusetIdRoute
  '/menu': typeof MenuIndexRoute
  '/menuset': typeof MenusetIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/$id': typeof MenuIdRoute
  '/menuset/$id': typeof MenusetIdRoute
  '/menu': typeof MenuIndexRoute
  '/menuset': typeof MenusetIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu/$id': typeof MenuIdRoute
  '/menuset/$id': typeof MenusetIdRoute
  '/menu/': typeof MenuIndexRoute
  '/menuset/': typeof MenusetIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu/$id'
    | '/menuset/$id'
    | '/menu'
    | '/menuset'
    | '/playground'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu/$id'
    | '/menuset/$id'
    | '/menu'
    | '/menuset'
    | '/playground'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/menu/$id'
    | '/menuset/$id'
    | '/menu/'
    | '/menuset/'
    | '/playground/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuIdRoute: typeof MenuIdRoute
  MenusetIdRoute: typeof MenusetIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenusetIndexRoute: typeof MenusetIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menuset/': {
      id: '/menuset/'
      path: '/menuset'
      fullPath: '/menuset'
      preLoaderRoute: typeof MenusetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menuset/$id': {
      id: '/menuset/$id'
      path: '/menuset/$id'
      fullPath: '/menuset/$id'
      preLoaderRoute: typeof MenusetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$id': {
      id: '/menu/$id'
      path: '/menu/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof MenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuIdRoute: MenuIdRoute,
  MenusetIdRoute: MenusetIdRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenusetIndexRoute: MenusetIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
